### ISSUE TITLE
data_template and integer

### ISSUE THREAD

**Issue by Mace404** [GregoryDosh/Home-Assistant-DreamScreen-Service#7]
Hi,

First on, great work on the script.
All the services are working great when I call them manually or with a script using a static value.

I added a light template for my Dreamscreen and most of it works great (Detects current status, can turn it on and off).
The thing I'm running in to is that data_template always outputs a string (because that is what Jinja does) and because of that I cannot use data_template to use any form of logic.

I'm using this on my light entity to set brightness:
```
  set_level:
    service: dreamscreen.set_brightness
    data_template:
      entity_id: dreamscreen.dreamscreen_4k
      brightness: "{{ (brightness / 2.55) | int }}"
```
and this gives the following error:
`ERROR (MainThread) [homeassistant.core] Invalid service data for dreamscreen.set_brightness: expected int for dictionary value @ data[‘brightness’]. Got ‘13’`

Also see this topic on the Home Assistant forum:
https://community.home-assistant.io/t/integer-list-in-data-template-converts-to-stings/63653
